## === 未开启开发者模式时 ===
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=51}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_1"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=52}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_2"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=53}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_3"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=54}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_4"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=55}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_5"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=56}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_6"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=57}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_7"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=58}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_8"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=59}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_9"}]}
execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=level,scores={backend=60}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"title.diy_10"}]}

## === 开启开发者模式时 ===
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=51}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_1"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=52}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_2"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=53}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_3"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=54}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_4"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=55}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_5"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=56}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_6"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=57}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_7"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=58}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_8"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=59}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_9"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=level,scores={backend=60}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext":[{"translate":"title.diy_10"},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"developer_mode.actionbar.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"developer_mode.actionbar.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"developer_mode.actionbar.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"developer_mode.actionbar.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
