# 非网易版
## === 未开启开发者模式时 ===
execute @e[name=isNetease,scores={settings=0}] ~~~ execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=counter,scores={backend=0}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"}]}}]}
execute @e[name=isNetease,scores={settings=0}] ~~~ execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=counter,scores={backend=1..}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"},{"translate":"actionbar.open.set_difficulty_line4"}]}}]}

## === 开启开发者模式时 ===
execute @e[name=isNetease,scores={settings=0}] ~~~ execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=counter,scores={backend=0}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext": [{"translate":"%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"}]}},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"actionbar.developer.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"actionbar.developer.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"actionbar.developer.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"actionbar.developer.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=isNetease,scores={settings=0}] ~~~ execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=counter,scores={backend=1..}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext": [{"translate":"%%s\n%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"},{"translate":"actionbar.open.set_difficulty_line4"}]}},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"actionbar.developer.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"actionbar.developer.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"actionbar.developer.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"actionbar.developer.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}

# 网易版
## === 未开启开发者模式时 ===
execute @e[name=isNetease,scores={settings=1}] ~~~ execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=counter,scores={backend=0}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"netease.actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"}]}}]}
execute @e[name=isNetease,scores={settings=1}] ~~~ execute @e[name=developerMode,scores={settings=0}] ~~~ execute @e[name=counter,scores={backend=1..}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"netease.actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"},{"translate":"actionbar.open.set_difficulty_line4"}]}}]}

## === 开启开发者模式时 ===
execute @e[name=isNetease,scores={settings=1}] ~~~ execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=counter,scores={backend=0}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext": [{"translate":"%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"netease.actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"}]}},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"actionbar.developer.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"actionbar.developer.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"actionbar.developer.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"actionbar.developer.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
execute @e[name=isNetease,scores={settings=1}] ~~~ execute @e[name=developerMode,scores={settings=1}] ~~~ execute @e[name=counter,scores={backend=1..}] ~~~ execute @a ~~~ titleraw @s actionbar {"rawtext":[{"translate":"%%s\n§r%%s","with":{"rawtext": [{"translate":"%%s\n%%s\n%%s\n%%s","with":{"rawtext":[{"translate":"actionbar.open.set_difficulty_line1"},{"translate":"netease.actionbar.open.set_difficulty_line2"},{"translate":"actionbar.open.set_difficulty_line3"},{"translate":"actionbar.open.set_difficulty_line4"}]}},{"translate":"%%s | %%s | %%s | %%s","with":{"rawtext":[{"translate":"actionbar.developer.oplevel","with":{"rawtext":[{"score":{"objective":"oplevel","name":"@s"}}]}},{"translate":"actionbar.developer.level_id","with":{"rawtext":[{"score":{"objective":"backend","name":"@e[name=level]"}}]}},{"translate":"actionbar.developer.time_played","with":{"rawtext":[{"score":{"objective":"time","name":"@e[name=playedMinute]"}},{"score":{"name":"@e[name=playedSecond]","objective":"time"}}]}},{"translate":"actionbar.developer.timeline","with":{"rawtext":[{"score":{"objective":"active","name":"@e[name=timeline]"}},{"score":{"name":"@e[name=timeline]","objective":"time"}}]}}]}}]}}]}
