tellraw @s {"rawtext":[{"translate":"feedback.help.line1"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line2"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line3"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line4"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line5"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line6"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line7"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line8"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line9"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line10"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line11"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line12"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line13"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line14"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line15"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line16"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line17"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line18"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line19"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line20"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line21"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line22"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line23"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line24"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line25"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line26"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line27"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line28"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line29"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line30"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line31"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line32"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line33"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line34"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line35"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line36"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line37"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line38"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line39"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line40"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line41"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line42"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line43"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line44"}]}
tellraw @s {"rawtext":[{"translate":"feedback.help.line45"}]}

scoreboard players set @e[name=soundPlayer] active 3