tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line1"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line2"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line3"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line4"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line5"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line6"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line7"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line8"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line9"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line10"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line11"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line12"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line13"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line14"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line15"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line16"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line17"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line18"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line19"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line20"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line21"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line22"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line23"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line24"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line25"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line26"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line27"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line28"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line29"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line30"}]}
tellraw @s {"rawtext":[{"translate":"chat.how_to_play.line31"}]}

scoreboard players set @e[name=soundPlayer] active 3